export const blue = '#3A36D5'
export const grey = '#CFD2D7'
export const bTaskee = '#FF8328'
export const PRIMARY_COLOR = '#FF8228'
export const SECONDARY_COLOR = '#1BB55C'
export const backgroundWhite = '#FAFAFA'
export const white = '#FFFFFF'
export const borderColor = '#D3D3D3'
export const gray = '#50555C'
export const lightGrey = '#EBEBEB'

export const gradientEnd = '#283236'
export const gradientStart = '#4C5775'
export const bottomTab = '#303A43'
export const DarkButton = '#1D252A'
export const black = '#1D252A'
export const green = '#09DFA1'
export const toggleGreen = '#09DFA1'
